### ISSUE TITLE
When I followed the contributor guildline,"make pre-commit" ourred an error"rstcheck Failed"

### ISSUE THREAD

**Issue by peter-ni-noob** [vacanza/holidays#1604] opened 2023-12-22 03:59 UTC
env:python 3.9 linux ubuntun 
rstcheck.................................................................Failed
- hook id: rstcheck
- exit code: 1

WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/contributing.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/changelog.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/index.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
docs/source/api.rst:4: (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".
docs/source/api.rst:4: (ERROR/3) Unknown directive type "automodule".
docs/source/api.rst:5: (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".
docs/source/api.rst:5: (ERROR/3) Unknown directive type "automodule".
docs/source/modules.rst:4: (INFO/1) No directive entry for "autosummary" in module "docutils.parsers.rst.languages.en".
docs/source/modules.rst:4: (ERROR/3) Unknown directive type "autosummary".
Error! Issues detected.

**Comment by peter-ni-noob** [comment] 2023-12-22 04:00
as usual ,I didn't change anything.

**Comment by PPsyrius** [comment] 2023-12-22 07:11
@peter-ni-noob Please ensure you've `pip install -r insert_filename_here.txt` everything in the `python-holidays\requirements` folder.

I'm still determining how to proceed if that doesn't work since I've only coded with WSL2 on Windows, but @arkid15r likely has the answer here.

**Comment by peter-ni-noob** [comment] 2023-12-22 12:04
Thank you for your help,I apply "make setup" to install this project,and I saw 
         pip install --upgrade pip
	pip install --requirement requirements/dev.txt
	pip install --requirement requirements/docs.txt
	pip install --requirement requirements/runtime.txt
	pip install --requirement requirements/tests.txt
in MakeFile,so I have installed everything in the python-holidays\requirements. I think the cause of the error is in docs/source/api.rst:4: (ERROR/3) Unknown directive type "automodule", but I dont really know rstcheck/(ㄒoㄒ)/~~.

**Comment by arkid15r** [comment] 2023-12-22 18:18
I was able to reproduce this with python3.9
I guess the best work around now would be commenting related [pre-commit configuration block](https://github.com/vacanza/python-holidays/blob/15f8335820d8082a9bb2d325259fa2c50af63f6d/.pre-commit-config.yaml#L58) out.

You might also need to run `make package` after `make setup` if you see `importlib_metadata.PackageNotFoundError: No package metadata was found for holidays` error.

Thanks for reporting this!

**Comment by peter-ni-noob** [comment] 2023-12-26 12:28
I just commented related [pre-commit configuration block](https://github.com/vacanza/python-holidays/blob/15f8335820d8082a9bb2d325259fa2c50af63f6d/.pre-commit-config.yaml#L58) out,and all passed.
the this issue will be closed.

**Comment by arkid15r** [comment] 2023-12-26 17:31
Yeah, that's a workaround for now. I'd prefer to not close the issue yet if you don't mind. At least until we look deeper into the problem.

**Comment by arkid15r** [comment] 2024-12-18 01:15
Closing as not planned after almost a year %)

**Closed by arkid15r** 2024-12-18 01:15 UTC
